server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.id.new_generator_mappings=true

# Configurações customizadas de autenticação
geosat.auth.access-token-expiration-minutes=30
geosat.auth.refresh-token-expiration-days=7

# Swagger / SpringDoc
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.operationsSorter=method

# Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

# Spring application name
spring.application.name=geosat-api
